name: Generate Pacman Arcade Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Pacman Contribution Graph
        uses: lowlighter/metrics@latest
        with:
          filename: pacman.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pacman: yes
          plugin_pacman_duration: 5
          plugin_pacman_greedy: yes

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
